apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kb-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "kb.zcx521.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601