apiVersion: v1
kind: Pod
metadata:
  name: test-projected-volume
spec:
  containers:
    - name: test-secret-volume
      image: busybox
      args:
        - sleep
        - "86400"
      volumeMounts:
        - name: mysql-cred
          mountPath: "/projected-volume"
          readOnly: true
        - name: mt
          mountPath: "/projected-mt"
          readOnly: true
        - name: cf
          mountPath: "/projected-cf"
  volumes:
    - name: mysql-cred
      projected:
        sources:
          - secret:
              name: user
          - secret:
              name: pass
    - name: mt
      projected:
        sources:
          - secret:
              name: mysecret
    - name: cf
      projected:
        sources:
          - configMap:
              name: cf